export const FETCH_ALL_ARTICLES = 'FETCH_ALL_ARTICLES';
export const SET_URL = 'SET_URL';
export const MODIFY_SEARCH = 'MODIFY_SEARCH';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';
export const OPEN_DISPLAY = 'OPEN_DISPLAY';
export const CLOSE_DISPLAY = 'CLOSE_DISPLAY';